apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/nithinnextjs/argocd-learning.git
    targetRevision: HEAD
    path: nginx-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      selfHeal: true